### ISSUE TITLE
Recent commits have broken builds

### ISSUE THREAD

**Issue by Earnestly** [fontforge/libuninameslist#12]
Hi,

Ever since https://github.com/fontforge/libuninameslist/commit/9fef08cc04ebf77ffc0230a785d8d86f110a4e3 I've been having build issues.

Initially because my `python` is `python3` by default, the addition of `python -3` resulted in this error:

```
Unknown option: -3
usage: /usr/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```

However I noticed it should honour `PYTHON`, with that I used `make PYTHON=python2` and all was well.  However when I tried to use a staged installation via `make PYTHON=python2 DESTDIR="$PWD"/stage install` I get these errors:

```
copying build/lib/uninameslist.py -> /usr/lib/python2.7/site-packages
error: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/uninameslist.py'
```

I believe `setup.py install` has `--root=` (and `--optimize=1` which is useful for tracking the `.pyc` and `.pyo` objects) which is equivalent to `DESTDIR`.

Currently I'm working around this by manually installing the files with the following:

```sh
install -Dm0644 uninameslist.h "$pkgdir"/usr/include/uninameslist.h
install -Dm0644 libuninameslist.pc "$pkgdir"/usr/lib/pkgconfig/libuninameslist.pc
install -Dm0644 .libs/libuninameslist.so "$pkgdir"/usr/lib/libuninameslist.so
ln -sf libuninameslist.so "$pkgdir"/usr/lib/libuninameslist.so.1
ln -sf libuninameslist.so "$pkgdir"/usr/lib/libuninameslist.so.1.0.2

cd py
python2 setup.py install --root="$pkgdir" --optimize=1
```

PS: The python build bits seem to be executed even during `make PYTHON=python2 check`, is this intentional?

**Comment by JoesCat** [comment]
Hi @Earnestly,
The main goal is to setup a configure.ac and Makefile.am which does not depend on autogen.sh or bootstrap.sh, and use as few dependencies as possible so that it's able to get used on other platforms easier. If successful, then what is learnt here can be applied towards the fontforge make build ecosystem.

Reading your issue, it's good feedback.
At this point, we can consider this like a version 1 install, which allows @jamadagni  to test-out his scripts and provides some people the ability to install - however, as you point-out, this version of install falls-over when you tried what you did.

We need something better.

I was looking at other setup ideas earlier (mentioned in https://github.com/fontforge/libuninameslist/pull/10 ). Any recomendations for version 2?

**Comment by Earnestly** [comment]
For what it's worth, I've been using `autoreconf -fi` for virtually all autotools projects, including this one.  Very rarely do I need to fall back on the project supplied "bootstrap", and it's usually never a good reason.

**Comment by JoesCat** [comment]
Hi @Earnestly, seems there's lots of documentation for python plus C library, but I needed something more in line with C library plus python wrapper. Autoconf seemed to have some variables available thru AM_PATH_PYTHON(), and I think pythondir seemed like the closest, allowing you direct python access without affecting autoconf's preference for /usr/local for C library install.
I think this patch resolves your problem plus allows some flexibility.

**Comment by JoesCat** [comment]
> PS: The python build bits seem to be executed even during make PYTHON=python2 check, is this intentional?

It appears python does this [Splitting the job up](https://docs.python.org/2/install/index.html#splitting-the-job-up). This requires a better, more detailed setup.py to ensure build_path and src_path are seen separately plus maybe further separation in py/Makefile.am.
...something to do later as I'm still bogged-down with other non-fontforge tasks that need doing.
...if someone wants to give it a try, those are the two files I'd think of to look at first.

**Comment by jamadagni** [comment]
Hi on a related note on my Kubuntu Xenial system with default Python as 2.7, the wrapper doesn't get installed for Python 3 (which I always use). Or should I open a separate issue for that?

**Comment by JoesCat** [comment]
@jamadagni, python2 && python3 might be a challenge, but appears it has been asked many times.
example: https://www.google.ca/search?q=makefile.am+python2+python3
something might be workable, but more searching will be needed for an elegant solution.

@Earnestly, I think I found something, but will need to try it when I have time - involves a lot of setup.py customization.

**Comment by JoesCat** [comment]
Hi @Earnestly,
unicode.org recently made version11 available and I would like to update this library to a new tag point.
There was concern about DESTDIR and building within the install directory.
Does this latest update work okay with you?

**Comment by Earnestly** [comment]
I'm not entirely sure if anything has influenced this issue with the recent changes.  The most I can see is I may not have to specify `PYTHON` for make but that's not really a major issue.

I don't mind manually installing because a stable build system is better than one which changes.  However the main issue is that I have to provide the appropriate version for the libraries, e.g.:

```sh
    install -Dm0644 .libs/libuninameslist.so "$pkgdir"/usr/lib/libuninameslist.so
    ln -sf libuninameslist.so "$pkgdir"/usr/lib/libuninameslist.so.1
    ln -sf libuninameslist.so "$pkgdir"/usr/lib/libuninameslist.so.1.0.2
```

This isn't ideal.  I don't know autotools (or really any configuration system) very well, so I can't offer suggestions, but I would plead that a stable build system, however mangled, is better than one which changes.

**Comment by JoesCat** [comment]
Yes - I'd like to make this stable before making a release tag point too.

The beta-tag point....ok, I think I understand what you mean....
github has an option to display 'pre-release', which I used:
https://github.com/fontforge/libuninameslist/releases

...I think what you are asking, is, instead of calling it tag point 20180408, it should have been tagpoint 20180408b or 20180408_beta since you aren't actually using the github webpage as a reference, but are using git itself.

**Comment by Earnestly** [comment]
I have no opinion on release tags or anything related to it.

I just wanted a working `install` target.  However I'm willing to stick with my manual installation if the cure is going to be worse than the disease.

**Comment by JoesCat** [comment]
Hi @Earnestly - I think we can safely close this issue, but will appreciate if you have feedback on the latest release - Thanks.

**Comment by Earnestly** [comment]
`make install` appears to create and install the correct set of symlinks.  The python2 aspect is no longer an issue as python2 is no longer supported meaning those components are no longer used.

**Comment by JoesCat** [comment]
Appears we can close this issue as resolved. Thanks for pointing-out an issue and also your feedback.
