### ISSUE TITLE
Build failure with clang

### ISSUE THREAD

**Issue by Biswa96** [fontforge/libuninameslist#25]
* Build environment - msys2/clang64
* clang - version 13.0.0 Target: x86_64-w64-windows-gnu
* Project version - 20211114
* Build output: [build-output.txt](https://github.com/fontforge/libuninameslist/files/7686520/build-output.txt)

How can I troubleshoot this issue? I can provide any further information if required.

**Comment by ctrlcctrlv** [comment]
Build command?

**Comment by Biswa96** [comment]
The build recipe can be found here https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libuninameslist/PKGBUILD. If I resolve all the environment variables in the configure command it will look like this (for clang64):

```
 ../libuninameslist-20211114/configure \
    --prefix=/clang64 \
    --build=x86_64-w64-mingw32 \
    --host=x86_64-w64-mingw32 \
    --target=x86_64-w64-mingw32 \
    --enable-shared \
    --enable-static
```

**Comment by ctrlcctrlv** [comment]
Thank you. I'm finding it a bit suspicious that on Windows you're providing both `--enable-shared` and `--enable-static`? My first thought is it might be related to https://trac.ffmpeg.org/ticket/1968. What if you `--disable-shared`?

**Comment by JoesCat** [comment]
Hi @Biswa96,
This problem appears to involve the file nameslist-dll.h
The purpose for this file is to advertise only the filenames we want to make available, while keeping internal functions private.

I think I recall reading that all windows libraries are dynamic, none are static.
and if we look at this file nameslist-dll.h we probably need to expand the 3rd line to also include 64bit definitions too.

#if defined _WIN32 || defined __CYGWIN__

expand to also include 64bit....

#if defined _WIN32 || defined __CYGWIN__ || defined _WIN64 || defined __CYGWIN64__

borrowing the idea above after reading...
https://cygwin.com/pipermail/cygwin-developers/2012-July/010732.html

I do not have a windows PC available here for testing this out, can you try testing the code?

**Comment by Biswa96** [comment]
> What if you --disable-shared?

Tried that but same error. BTW, we want both static and shared libraries.

> expand to also include 64bit....

That does not solve the issue. `_WIN32` is defined for both x86 and x86_64[^1]

> I do not have a windows PC available here for testing this out, can you try testing the code?

If you wish I can ask someone to add msys2 build environment in CI.

[^1]: https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros

**Comment by JoesCat** [comment]
> If you wish I can ask someone to add msys2 build environment in CI.

That may be a way for me to test it.
Last night, I have also began looking at ways to get github workflow to 
process MSYS2 - I'll see if I can get it to run tonight so that I can 
duplicate your problem and try to figure-out a solution.

**Comment by JoesCat** [comment]
Adding the additional `|| defined _WIN64 || defined __CYGWIN64__` appears to be beneficial. Without it, it did not completely run make check, and with it, it ran all make check successfully.
[without WIN64 (test failed)](https://github.com/fontforge/libuninameslist/runs/4577923453?check_suite_focus=true)
[with WIN64 (test passed)](https://github.com/JoesCat/libuninameslist/runs/4602943834?check_suite_focus=true)

Might be worth noting.

However, it didn't fix the original problem.... that needs something else...or more

**Comment by Biswa96** [comment]
I can see this in both tests:

```
# TOTAL: 4
# PASS:  4
```

What happened is that - By default, GitHub Actions terminates any running jobs if any job in a matrix fails. Here clang64 fails before mingw64. So, GHA terminates mingw64 without finishing it. This behavior can be configured with `fail-fast: false` option.

**Comment by JoesCat** [comment]
Thanks - didn't know that.

**Comment by JoesCat** [comment]
It appears that MSYS2 is quietly injecting it's own copies of the decl import/export definitions. I've turned-off adding that information in file nameslist-dll.h if it sees clang.

Also tested with "./configure --enable-shared --enable-static --enable-frenchlib" and that appeared okay too. I think the problem is resolved and we can close this issue.

**Comment by Biswa96** [comment]
Thank you for fixing this issue.
