### ISSUE TITLE
wrong library version 

### ISSUE THREAD

**Issue by lemzwerg** [fontforge/libuninameslist#7]
On my openSuSE Leap 42.1 box, the system comes with libuninameslist.so.0.0.2 (in /usr/lib64).  I've installed the library from git into /usr/local/lib64, resulting in libuninameslist.so.0.0.5.  According to the libtool rules of versioning, those two versions should be ABI compatible.  However, this is *not* correct: For example, the git version contains function `uniNamesList_name`, not present in the 0.0.2 version. Thus the version should be e.g. '0.1.0' or something similar.

This is a very severe problem!  For some reasons, compiling and installing current FontForge works fine, but execution fails with
```
fontforge: symbol lookup error: /usr/local/lib64/libgutils.so.2: undefined symbol: uniNamesList_name
```
Looking into `configure.ac`, I see that the versioning system is completely broken, using only libtool versions of the form X:Y:0 for the `-version-info` flag.  This simply doesn't work!  You really need the triplet X:Y:Z to get the right DLL version.

**Comment by lemzwerg** [comment]
After some investigation it seems that the fontforge issue is a different problem – it doesn't properly recognize very old libuninameslist versions.  However, the libtool versioning problem is still present: I think it would be a good thing to follow the rules given in the libtool manual...  Below is a possible patch (`configure.ac.diff.xz.base64`).
```
/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4AmIAutdADIaSQnC/BF9UN4KT0fWEbHoWo/Ga31TYOEC
vf0K5tVFIASI2sDQ1oMXW66q269iztnffBYqOXe3byHgWVg8OIQSsyYnQyhDcDyCEXqgmO3k8nHA
XTEveAsSTVmAevmyrFg4FVfSgDNtKM2FIqfyDdVc95t2XAVIl8iDmCYu+drxuzIJoOA0quVMoLUQ
0UxH6b7Wr/ognnFCyorK1vgndS/r2Z/O7Ct7usgCD4YplHi+w2U4UeEBUi0Jvew5M2kyxRUK/iIp
n/Rg3y7nnDMpxIUNhKWimCgKVxwlqwG6SAZcA+IorqR6bXTXKi17j5rIOQNTa70xvc9KDLFuS+Jv
5J2z3q/kpXmbu+6Ld4fsmg6AjrTiRRmJugrycj4ISaNg+CTC7M4Fzo27//0I3fde7msc71ZdDZZP
ppit3Ll+n2Yr6RgsaXr1dE52hrHFCJIEWLDNlXfp3o5JqrKbiYew6y8N60OdvrqzDx8TzamuDpRd
CFsIIHG/ZypajTRCuurJc+ZtRkFPHTogMdntqnC/hVEV9leEiMGiuPrqFMGayEntHkQhBU+WNLfp
muYq1rsyRe0pb+N0BzgZlw+SgX/xo+8ZuhvqE/5nYnBUj2Vmlq8za9TRq8mxhHfNJ9fz9yYwtcgg
CDVxdi2jlYxZVQnQ+bk5lYFDJo66QVWr2l12n+DHK3TlMBUpRsuSeKVc7OTAXvhTHzGJv5RUTP0j
wXnASiOveAdM7AC8BhUbmWnzZhIf2NjTTiIGyo1wMYwmxxIb2U2Bq3VCnDvxufPHGGvUFeNg7rpK
zsQscCn1dIglJzUTTHbjkbdN9ZFvUtFwmx4Z4Mk2CrGL3SlJw2LcgMe6L0tSYeORY4mo2PnK4Ca6
OmqKVoRyQjs8nBSmZTMoGW0uMcwShYbxth4iXCRDsPdauscD79Ud3s2uhVg8cfOssZAMR+x6jdE3
QQkJXSYHgWvAD73bQSiHutf55YBEMnkyUHZcWqBBWBO93y+GQQAAZ7/svAiREP4AAYcGiRMAAIXh
kcGxxGf7AgAAAAAEWVo=
```

**Comment by lemzwerg** [comment]
Just for completeness: The fontforge issue was a problem on my side.

**Comment by JoesCat** [comment]
It took a fair bit of digging around, but I think I see what you mean - From this:
https://developer.gnome.org/programming-guidelines/stable/versioning.html.en
In summary...
Libraries have a libtool version of the form current:revision:age.
Libraries have a package version of the form major.minor.micro.
...unfortunately, they might not necessarily be the same values...

I can't extract the patch you presented above.
Can you create a pull request, or email the diff as an attachment?
...when mentioning X:Y:Z for the DLL, also be aware that Linux and BSD also apply the values differently too. See warning here: https://autotools.io/libtool/version.html

**Comment by lemzwerg** [comment]
Exactly!  Due to differences in DLL versioning between different platforms it is in general a bad idea to make the DLL version identical to the library version.

**Comment by JoesCat** [comment]
Thanks - learnt something new about base64.
I've added your patch as a branch (not yet in mainline) since it bumps-up the numbers, but I'd prefer to see the numbers bump-up when unicode 9.0 appear.
The French tables will also need correcting as well.

**Comment by lemzwerg** [comment]
OK.  I also suggest to add a `libuninameslist.pc` file for pkg-config, which makes both compiling and linking much easier.

**Comment by JoesCat** [comment]
autoreconf -i
automake
will generate libuninameslist.pc
...word of warning... some pkg-config are not reliable for finding user generated libraries in non-distro locations, such as /usr/local - mainly older distros, and/or older pkg-config, the BSDs might also fall into this category, so it may also include MACs and Windows based machines. If you're having trouble finding the library, you may need to use AC_SEARCH and/or AC_CHECK
...but this is all going off-topic related to this issue - I think this issue is resolved - Thanks.

**Comment by Flameeyes** [comment]
@JoesCat I'd suggest not to use AC_SEARCH/AC_CHECK if you're using PKG_CHECK_MODULES. Instead tell the users to (if needed) pass FOO_CFLAGS/FOO_LIBS at configure time.
